# Generated by Django 6.0.5 on 2026-05-26 17:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlacementPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_features', models.JSONField(help_text='The exact academic data JSON sent to the AIML model')),
                ('prediction_result', models.CharField(help_text='Output prediction from the model', max_length=255)),
                ('probability_score', models.FloatField(help_text='Confidence or probability percentage')),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentPerformanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cgpa', models.FloatField(help_text='Current CGPA of the student')),
                ('attendance_percentage', models.FloatField(help_text='Overall attendance percentage')),
                ('number_of_backlogs', models.IntegerField(default=0, help_text='Number of active backlogs')),
                ('coding_rating', models.IntegerField(help_text='Programming skill rating (1 to 5)')),
                ('semester', models.IntegerField(help_text='Current Semester (1 to 8)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
